var images = [];
var i = 0;
images[i++] = { "image": "1354488708-0352065.jpg"};
images[i++] = { "image": "compassion-1936.jpg"};
images[i++] = { "image": "himalayas-1933.jpg"};
images[i++] = { "image": "milarepa-the-one-who-harkened-1925.jpg"};
images[i++] = { "image": "mount-of-five-treasures-two-worlds-1933.jpg"};
images[i++] = { "image": "rerih5.jpg"};
images[i++] = { "image": "TrekWorld_Nicholas-Roerich_Kanchendzonga-1944.jpg"};